#!/usr/bin/env python3
"""
Regenerates FUNCTION-MAP.md: every top-level function and exported symbol,
with the file and line it lives on. Run after any change that adds or moves
a function, from the repo root:   python3 gen_map.py
The point is that finding code should cost one file read, not a dozen greps.
"""
import glob, os, re, sys

# This script lives at the repo root, not tools/gen_map.py. It used to take
# the parent of ITS OWN directory, assuming a tools/ subdirectory that
# doesn't exist, which put ROOT one level *above* the actual repo -- chdir'd
# there, the [0-9][0-9]_*.js glob silently matched nothing, and the script
# wrote a near-empty FUNCTION-MAP.md outside the repo entirely instead of
# updating the real, tracked one.
ROOT = os.path.dirname(os.path.abspath(__file__))
os.chdir(ROOT)

FN = re.compile(r'^(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(')
CONST = re.compile(r'^(?:const|let|var)\s+([A-Z][A-Z0-9_]{2,})\s*=')

# Routes come in three shapes and this used to match only the first, so the
# generated map's route table silently omitted EVERY prefix and regex route --
# /lists/:user/:slug, /channels/..., /api/scrobble..., /:config/manifest.json,
# /:config/catalog/... None of them appeared, and the map is what someone
# builds a route inventory from.
ROUTE_PATTERNS = [
    # path === "/api/thing"
    (re.compile(r'path\s*===\s*"([^"]+)"'), lambda m: m.group(1)),
    # path.startsWith("/api/scrobble")
    (re.compile(r'path\.startsWith\(\s*"([^"]+)"'), lambda m: m.group(1) + "*"),
    # path.match(/^\/lists\/([^/]+)\/([^/]+)$/)
    (re.compile(r'path\.match\(\s*/(.+?)/[gimsuy]*\s*\)'), lambda m: "re:" + m.group(1)),
    # m = path.match(...) assigned first, matched on the next line
    (re.compile(r'^\s*m\s*=\s*path\.match\(\s*/(.+?)/[gimsuy]*\s*\)'), lambda m: "re:" + m.group(1)),
]

files = sorted(glob.glob('[0-9][0-9]_*.js'))
rows, routes = [], []
for f in files:
    n = int(f[:2])
    for i, line in enumerate(open(f, encoding='utf-8', errors='replace'), 1):
        m = FN.match(line)
        if m: rows.append((m.group(1), f, i))
        m = CONST.match(line)
        if m: rows.append((m.group(1), f, i))
        for pattern, render in ROUTE_PATTERNS:
            for r in pattern.finditer(line):
                routes.append((render(r), f, i))

out = ['# Function Map', '',
       '_Generated by `gen_map.py`. Do not edit by hand._', '',
       f'{len(rows)} top-level symbols across {len(files)} files.', '',
       '## Routes', '', '| path | file:line |', '|---|---|']
for p, f, i in sorted(set(routes)):
    out.append(f'| `{p}` | {f}:{i} |')
out += ['', '## Symbols', '', '| symbol | file:line |', '|---|---|']
for name, f, i in sorted(rows, key=lambda r: r[0].lower()):
    out.append(f'| `{name}` | {f}:{i} |')

# newline='\n': on Windows, text mode would otherwise write CRLF and the
# committed LF map would look stale (see .gitattributes).
open('FUNCTION-MAP.md', 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print(f'FUNCTION-MAP.md: {len(rows)} symbols, {len(set(routes))} routes, {os.path.getsize("FUNCTION-MAP.md"):,} bytes')
